# **Praktikum 4: Klasifikasi dengan ANN**

In [1]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/80/6f/57d36f6507e432d7fc1956b2e9e8530c5c2d2bfcd8821bcbfae271cd6688/tensorflow-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.14.0 from https://files.pythonhosted.org/packages/ad/6e/1bfe367855dd87467564f7bf9fa14f3b17889988e79598bc37bf18f5ffb6/tensorflow_intel-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


## **Pra Pengolahan Data**

### **Langkah 1 - Import Library**

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

### **Langkah 2 - Load Data**

In [4]:
dataset = pd.read_csv('../data/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

Cek Data (X)

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


### **Langkah 3 - Encoding Data Kategorikal**

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### **Langkah 4 - Encoding Kolom "Geography" dengan One Hot Encoder**

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### **Langkah 5 - Split Data**

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### **Langkah 6 - Scaling Fitur**

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## **Membuat Model ANN**

### **Langkah 1 - Inisiasi Model ANN**

In [12]:
ann = tf.keras.models.Sequential()

### **Langkah 2 - Membuat Input Layer dan Hidden Layer Pertama**

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### **Langkah 3 - Membuat Hidden Layer Kedua**

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### **Langkah 4 - Membuat Output Layer**

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## **Training Model**

### **Langkah 1 - Compile Model (Menyatukan Arsitektur) ANN**

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### **Langkah 2 - Fitting Model**

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6722 - accuracy: 0.6263
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4788 - accuracy: 0.8020
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4509 - accuracy: 0.8058
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4353 - accuracy: 0.8102
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4252 - accuracy: 0.8125
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4189 - accuracy: 0.8159
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4139 - accuracy: 0.8188
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4097 - accuracy: 0.8184
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4054 - accuracy: 0.8219
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4011 - accura

## **Membuat Prediksi**

Diberikan informasi sebagai berikut,
- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40 years old
- Tenure: 3 years
- Balance: $ 60000
- Number of Products: 2
- Does this customer have a credit card ? Yes
- Is this customer an Active Member: Yes
- Estimated Salary: $ 50000
- Apakah customer tersebut perlu dipertahankan?

### **Modelkan Data Baru dan Buat Prediksi**

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 187ms/step
[[False]]


### **Prediksi Dengan Data Testing**

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### **Cek Akurasi dan Confusion Matrix**

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1494  101]
 [ 188  217]]


0.8555